Integration tests
NovatecConsulting/camunda-bpmn-documentation-generator pull request #25
Opened 2022-01-14 11:57 UTC by ykstr

2022-01-21 14:29 UTC, ahsNT commented
Please squash into one commit with a message that matches our git conventions

2022-01-21 16:15 UTC, ahsNT requested changes

2022-01-28 13:40 UTC, ykstr commented on .github/workflows/continous-integration.yml
> +        run: cd ./test-project; mvn clean install
Shouldn't that belong to the main project instead of the maven test project?

2022-01-28 13:43 UTC, ykstr commented
It seems this pull request was linked to the wrong commits

2022-01-28 13:43 UTC, closed without merging